import React, { useState } from 'react'
  //The application must display the total number of collected feedback for each category. 

  const Button = ({ handleClick, text }) => <button onClick={handleClick}>{text}</button>
  const Statistic =  ({text,value}) =>  <td>{text} {value}</td>
  const Statistics =  ({good,neutral,bad,all}) => {
 /*
  Warning: validateDOMNesting(...): <tr> cannot appear as a child of <table>.
   Add a <tbody>, <thead> or <tfoot> to your code to match the DOM tree generated by the browser.
   Solution Add a <tbody>, on <table>
 */

  return(
 
      <table>
        <tbody>
          <tr>
            <Statistic text="good" value ={good} />
          </tr>
          <tr>
          <Statistic text="neutral" value ={neutral} />
          </tr>
          <tr>
          <Statistic text="bad" value ={bad} />
          </tr>
          <tr>
          <Statistic text="average" value ={(good + (neutral*0) + bad*(-1))/all} />
          </tr>
          <tr>
          <Statistic text="positive" value ={good/(all/100)} />
          </tr>
        </tbody>
      </table>
  )
}

const FeedbackSystem = ()=>{
  const [good, setGood] = useState(0)
  const [neutral, setNeutral] = useState(0)
  const [bad, setBad] = useState(0)
  const [all, setAll] = useState(0)

  const setIncreaseByOneGood = () => {
    setAll(all + 1)
    setGood(good + 1)   
  }
  const setIncreaseByOneNeutral = () => {
    setAll(all + 1)
    setNeutral(neutral + 1)
  }
  const setIncreaseByOneBad = () => {
    setAll(all + 1)
    setBad(bad + 1)
  }
  
  if( all === 0 ){
    return (
      <div>
        <Button handleClick={setIncreaseByOneGood} text="good"/>
        <Button handleClick={setIncreaseByOneNeutral} text="neutral"/>
        <Button handleClick={setIncreaseByOneBad} text="bad"/>
        <h1>Statistics</h1>
        <p>No feedback given</p>
      </div>
    )
  }
  return (
    <div>
        <Button handleClick={setIncreaseByOneGood} text="good"/>
        <Button handleClick={setIncreaseByOneNeutral} text="neutral"/>
        <Button handleClick={setIncreaseByOneBad} text="bad"/>
        <h1>Statistics</h1>
      <Statistics good={good} neutral={neutral} bad={bad} all={all}/>
    </div>
  )
}

const App = () => {
  return (
    <div>
      <h1>give feedback</h1>
      <FeedbackSystem/>
    </div>
  )
}

export default App